---
# tasks file for tomcat

- name: 'add group "tomcat"'
  group: 
    name: tomcat
    state: present

- name: 'create a user tomcat in tomcat group'
  user:
    name: tomcat
    group: tomcat
    update_password: always
    password: $6$wxi1Nn30vZJ2Wy7a$xJKixBl0tPXCW.jvqMlW4AfjDy1vrfPAwzR8bf/ekSBgMUeDXdobbPIuROG/e4nv.7jPIw6CRKuFhPyggWiEk0

- name: update sudo access to tomcat user
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%tomcat'
    line: '%tomcat ALL=(ALL) NOPASSWD: ALL'

- name: Create multiple users
  become: true
  vars:
    user_name:
         - name: test1
           comment: "This is test1 user"
         - name: test2
           comment: "This is test2 user"
         - name: test3
           comment: "This is test3 user"
- name: create test user
  user:
    name: "{{item.name}}"
    comment: "{{item.comment}}"
  loop: "{{user_name}}"
  #state: absent

